// <auto-generated />
namespace Online_book_shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class altr_book_prop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(altr_book_prop));
        
        string IMigrationMetadata.Id
        {
            get { return "202005240740575_altr_book_prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
