// <auto-generated />
namespace Online_book_shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class book_bookProperty_tbl_update2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(book_bookProperty_tbl_update2));
        
        string IMigrationMetadata.Id
        {
            get { return "202005170732093_book_bookProperty_tbl_update2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
