// <auto-generated />
namespace Online_book_shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _30 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_30));
        
        string IMigrationMetadata.Id
        {
            get { return "202005091445152_3.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
