// <auto-generated />
namespace Online_book_shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dead_line_date_for_book_pack : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dead_line_date_for_book_pack));
        
        string IMigrationMetadata.Id
        {
            get { return "202111011330099_dead_line_date_for_book_pack"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
