// <auto-generated />
namespace Online_book_shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_tbl_saletypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_tbl_saletypes));
        
        string IMigrationMetadata.Id
        {
            get { return "202104131258529_add_tbl_saletypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
